language: python
python: 2.7
env:
  - TOX_ENV=pep8
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=flake8
install:
  - pip install --upgrade pip setuptools tox virtualenv .
matrix:
  allow_failures:
    - env: TOX_ENV=py26
    - env: TOX_ENV=py34
script:
  - "tox -e $TOX_ENV"
notifications:
  email: false
